{{- if and .Values.devpodIngress .Values.devpodIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.devpodIngress.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- with .Values.devpodIngress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "43200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "43200"
    nginx.org/websocket-services: loft
    {{- with .Values.devpodIngress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.devpodIngress.ingressClass }}
  ingressClassName: {{ .Values.devpodIngress.ingressClass }}
  {{- end }}
  rules:
    - host: {{ .Values.devpodIngress.host | quote }}
      http:
        paths:
          - path: {{ .Values.devpodIngress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: loft
                port:
                  number: 80
  {{- if .Values.devpodIngress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.devpodIngress.host | quote }}
      {{- if .Values.devpodIngress.tls.secret }}
      secretName: {{ .Values.devpodIngress.tls.secret }}
      {{- end }}
  {{- end }}
{{- end }}
