{{- if .Values.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: loft-manager-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    loft.sh/version: {{ .Chart.Version }}
  {{- if or .Values.commonAnnotations .Values.secretAnnotations }}
    {{- with .Values.secretAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  config: {{ toYaml .Values.config | b64enc }}
{{- end }}

{{- if .Values.agentValues }}
---
apiVersion: v1
kind: Secret
metadata:
  name: loft-default-agent-values
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if or .Values.commonAnnotations .Values.agentSecretAnnotations }}
    {{- with .Values.agentSecretAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  values: {{ toYaml .Values.agentValues | b64enc }}
{{- end }}

{{- if .Values.agentOnly }}
---
apiVersion: v1
kind: Secret
metadata:
  name: loft-agent-connection
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if or .Values.commonAnnotations .Values.agentSecretAnnotations }}
    {{- with .Values.agentSecretAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  token: {{ toYaml .Values.token | b64enc }}
  url: {{ toYaml .Values.url | b64enc }}
{{- end }}

{{- if and .Values.additionalCA (not .Values.insecureSkipVerify) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: loft-additional-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if or .Values.commonAnnotations .Values.agentSecretAnnotations }}
    {{- with .Values.agentSecretAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  ca.crt: {{ .Values.additionalCA | quote }}
{{- end }}
