{{- if (and .Values.agentOnly (include "loft.isLeastPrivilegeModeEnabled" .)) }}
{{- $lpmValues := include "loft.leastPrivilegeModeValues" . | fromJson }}
{{- if eq true $lpmValues.role.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vcluster-platform-agent
  labels:
    app: {{ template "loft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "loft.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: vcluster-platform-agent
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
